/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ifuttctsjfogiaujjets";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmdXR0Y3RzamZvZ2lhdWpqZXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxNjIxODMsImV4cCI6MjA4MDczODE4M30.ysKLH0PmvSLCq0rLvMggPEvAfHClp3RXKV-3rd5COE0";