/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hpflagcawwhruiwxpiip";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwZmxhZ2Nhd3docnVpd3hwaWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwMTAxNDIsImV4cCI6MjA4MTU4NjE0Mn0.Yz9Fo98Cadw6bqTLoXs5vB1hCdlFOZpm8UQszQbZ8vw";